// This file is generated by the Open edX generate-mfe-i18n-imports.
// Refer to docs yada yada ...
//

import messages1frontendapplearning from './messages/frontend-app-learning';
import messages1frontendcomponentfooter from './messages/frontend-component-footer';
import messages1frontendcomponentheader from './messages/frontend-component-header';

export default [
  messages1frontendapplearning,
  messages1frontendcomponentfooter,
  messages1frontendcomponentheader,
];
