// This file is generated by the Open edX generate-mfe-i18n-imports.
// Refer to the Open edX developer reference docs for more info about the i18n:
//  - https://docs.openedx.org/en/latest/developers/references/index.html
//
export default [];
