// This file is generated by the Open edX frontend-platform's i18n-imports commands.
//

import messages2frontendapplearning from './messages/frontend-app-learning';

export default [
  messages2frontendapplearning,
];
