// This file is generated by the Open edX generate-mfe-i18n-imports.


// Refer to docs yada yada ...


//


import messages_0_ar from './ar.json';
import messages_1_de from './de.json';
import messages_2_de_DE from './de_DE.json';
import messages_3_es_419 from './es_419.json';
import messages_4_fr from './fr.json';
import messages_5_fr_CA from './fr_CA.json';
import messages_6_hi from './hi.json';
import messages_7_it from './it.json';
import messages_8_it_IT from './it_IT.json';
import messages_9_pt from './pt.json';
import messages_10_pt_PT from './pt_PT.json';
import messages_11_ru from './ru.json';
import messages_12_uk from './uk.json';
import messages_13_zh_CN from './zh_CN.json';


const messages = {
  'zh-cn': messages_13_zh_CN,
  'uk': messages_12_uk,
  'ru': messages_11_ru,
  'pt-pt': messages_10_pt_PT,
  'pt': messages_9_pt,
  'it-it': messages_8_it_IT,
  'it': messages_7_it,
  'hi': messages_6_hi,
  'fr-ca': messages_5_fr_CA,
  'fr': messages_4_fr,
  'es-419': messages_3_es_419,
  'de-de': messages_2_de_DE,
  'de': messages_1_de,
  'ar': messages_0_ar,
};


export default messages;