// This file is generated by the Open edX generate-mfe-i18n-imports.
// Refer to docs yada yada ...
//

import messages0ar from './ar.json';
import messages1de from './de.json';
import messages2de_DE from './de_DE.json';
import messages3es_419 from './es_419.json';
import messages4fr from './fr.json';
import messages5fr_CA from './fr_CA.json';
import messages6hi from './hi.json';
import messages7it from './it.json';
import messages8it_IT from './it_IT.json';
import messages9pt from './pt.json';
import messages10pt_PT from './pt_PT.json';
import messages11ru from './ru.json';
import messages12uk from './uk.json';
import messages13zh_CN from './zh_CN.json';
const messages = {
  'zh-cn': messages13zh_CN,
  'uk': messages12uk,
  'ru': messages11ru,
  'pt-pt': messages10pt_PT,
  'pt': messages9pt,
  'it-it': messages8it_IT,
  'it': messages7it,
  'hi': messages6hi,
  'fr-ca': messages5fr_CA,
  'fr': messages4fr,
  'es-419': messages3es_419,
  'de-de': messages2de_DE,
  'de': messages1de,
  'ar': messages0ar,
};
export default messages;
