// This file is generated by the Open edX generate-mfe-i18n-imports.
// Refer to docs yada yada ...
//

import messages0ar from './ar.json';
import messages1de from './de.json';
import messages2es_419 from './es_419.json';
import messages3fr_CA from './fr_CA.json';
import messages4ru from './ru.json';
import messages5uk from './uk.json';
import messages6zh_CN from './zh_CN.json';
const messages = {
  'ar': messages0ar,
  'zh-cn': messages6zh_CN,
  'uk': messages5uk,
  'ru': messages4ru,
  'fr-ca': messages3fr_CA,
  'es-419': messages2es_419,
  'de': messages1de,
};
export default messages;
