// This file is generated by the Open edX generate-mfe-i18n-imports.


// Refer to docs yada yada ...


//


import messages_0_ar from './ar.json';
import messages_1_de from './de.json';
import messages_2_es_419 from './es_419.json';
import messages_3_fr_CA from './fr_CA.json';
import messages_4_ru from './ru.json';
import messages_5_uk from './uk.json';
import messages_6_zh_CN from './zh_CN.json';


const messages = {
  'zh-cn': messages_6_zh_CN,
  'uk': messages_5_uk,
  'ru': messages_4_ru,
  'fr-ca': messages_3_fr_CA,
  'es-419': messages_2_es_419,
  'de': messages_1_de,
  'ar': messages_0_ar,
};


export default messages;